/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardStaffManagementImport } from './routes/dashboard/staff-management'
import { Route as AuthLoginImport } from './routes/auth.login'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardcardRoutesRouteImport } from './routes/dashboard/(card-routes)/route'
import { Route as DashboardSettingsIndexImport } from './routes/dashboard/settings/index'
import { Route as DashboardRequestManagementIndexImport } from './routes/dashboard/request-management/index'
import { Route as DashboardcardRoutesIndexImport } from './routes/dashboard/(card-routes)/index'
import { Route as DashboardSettingsProfileImport } from './routes/dashboard/settings/profile'
import { Route as DashboardRequestManagementNewImport } from './routes/dashboard/request-management/new'
import { Route as DashboardRequestManagementIdImport } from './routes/dashboard/request-management/$id'
import { Route as DashboardcardRoutesInventoryImport } from './routes/dashboard/(card-routes)/inventory'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardStaffManagementRoute = DashboardStaffManagementImport.update({
  id: '/staff-management',
  path: '/staff-management',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardSettingsRouteRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardcardRoutesRouteRoute = DashboardcardRoutesRouteImport.update({
  id: '/(card-routes)',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardSettingsIndexRoute = DashboardSettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)

const DashboardRequestManagementIndexRoute =
  DashboardRequestManagementIndexImport.update({
    id: '/request-management/',
    path: '/request-management/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardcardRoutesIndexRoute = DashboardcardRoutesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardcardRoutesRouteRoute,
} as any)

const DashboardSettingsProfileRoute = DashboardSettingsProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)

const DashboardRequestManagementNewRoute =
  DashboardRequestManagementNewImport.update({
    id: '/request-management/new',
    path: '/request-management/new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardRequestManagementIdRoute =
  DashboardRequestManagementIdImport.update({
    id: '/request-management/$id',
    path: '/request-management/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardcardRoutesInventoryRoute =
  DashboardcardRoutesInventoryImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => DashboardcardRoutesRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/(card-routes)': {
      id: '/dashboard/(card-routes)'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardcardRoutesRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/staff-management': {
      id: '/dashboard/staff-management'
      path: '/staff-management'
      fullPath: '/dashboard/staff-management'
      preLoaderRoute: typeof DashboardStaffManagementImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/(card-routes)/inventory': {
      id: '/dashboard/(card-routes)/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardcardRoutesInventoryImport
      parentRoute: typeof DashboardcardRoutesRouteImport
    }
    '/dashboard/request-management/$id': {
      id: '/dashboard/request-management/$id'
      path: '/request-management/$id'
      fullPath: '/dashboard/request-management/$id'
      preLoaderRoute: typeof DashboardRequestManagementIdImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/request-management/new': {
      id: '/dashboard/request-management/new'
      path: '/request-management/new'
      fullPath: '/dashboard/request-management/new'
      preLoaderRoute: typeof DashboardRequestManagementNewImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileImport
      parentRoute: typeof DashboardSettingsRouteImport
    }
    '/dashboard/(card-routes)/': {
      id: '/dashboard/(card-routes)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardcardRoutesIndexImport
      parentRoute: typeof DashboardcardRoutesRouteImport
    }
    '/dashboard/request-management/': {
      id: '/dashboard/request-management/'
      path: '/request-management'
      fullPath: '/dashboard/request-management'
      preLoaderRoute: typeof DashboardRequestManagementIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexImport
      parentRoute: typeof DashboardSettingsRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardcardRoutesRouteRouteChildren {
  DashboardcardRoutesInventoryRoute: typeof DashboardcardRoutesInventoryRoute
  DashboardcardRoutesIndexRoute: typeof DashboardcardRoutesIndexRoute
}

const DashboardcardRoutesRouteRouteChildren: DashboardcardRoutesRouteRouteChildren =
  {
    DashboardcardRoutesInventoryRoute: DashboardcardRoutesInventoryRoute,
    DashboardcardRoutesIndexRoute: DashboardcardRoutesIndexRoute,
  }

const DashboardcardRoutesRouteRouteWithChildren =
  DashboardcardRoutesRouteRoute._addFileChildren(
    DashboardcardRoutesRouteRouteChildren,
  )

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardcardRoutesRouteRoute: typeof DashboardcardRoutesRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardStaffManagementRoute: typeof DashboardStaffManagementRoute
  DashboardRequestManagementIdRoute: typeof DashboardRequestManagementIdRoute
  DashboardRequestManagementNewRoute: typeof DashboardRequestManagementNewRoute
  DashboardRequestManagementIndexRoute: typeof DashboardRequestManagementIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardcardRoutesRouteRoute: DashboardcardRoutesRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardStaffManagementRoute: DashboardStaffManagementRoute,
  DashboardRequestManagementIdRoute: DashboardRequestManagementIdRoute,
  DashboardRequestManagementNewRoute: DashboardRequestManagementNewRoute,
  DashboardRequestManagementIndexRoute: DashboardRequestManagementIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardcardRoutesIndexRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/staff-management': typeof DashboardStaffManagementRoute
  '/dashboard/inventory': typeof DashboardcardRoutesInventoryRoute
  '/dashboard/request-management/$id': typeof DashboardRequestManagementIdRoute
  '/dashboard/request-management/new': typeof DashboardRequestManagementNewRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/request-management': typeof DashboardRequestManagementIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/staff-management': typeof DashboardStaffManagementRoute
  '/dashboard/inventory': typeof DashboardcardRoutesInventoryRoute
  '/dashboard/request-management/$id': typeof DashboardRequestManagementIdRoute
  '/dashboard/request-management/new': typeof DashboardRequestManagementNewRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard': typeof DashboardcardRoutesIndexRoute
  '/dashboard/request-management': typeof DashboardRequestManagementIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/(card-routes)': typeof DashboardcardRoutesRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/staff-management': typeof DashboardStaffManagementRoute
  '/dashboard/(card-routes)/inventory': typeof DashboardcardRoutesInventoryRoute
  '/dashboard/request-management/$id': typeof DashboardRequestManagementIdRoute
  '/dashboard/request-management/new': typeof DashboardRequestManagementNewRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/(card-routes)/': typeof DashboardcardRoutesIndexRoute
  '/dashboard/request-management/': typeof DashboardRequestManagementIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/settings'
    | '/auth/login'
    | '/dashboard/staff-management'
    | '/dashboard/inventory'
    | '/dashboard/request-management/$id'
    | '/dashboard/request-management/new'
    | '/dashboard/settings/profile'
    | '/dashboard/request-management'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/dashboard/staff-management'
    | '/dashboard/inventory'
    | '/dashboard/request-management/$id'
    | '/dashboard/request-management/new'
    | '/dashboard/settings/profile'
    | '/dashboard'
    | '/dashboard/request-management'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/(card-routes)'
    | '/dashboard/settings'
    | '/auth/login'
    | '/dashboard/staff-management'
    | '/dashboard/(card-routes)/inventory'
    | '/dashboard/request-management/$id'
    | '/dashboard/request-management/new'
    | '/dashboard/settings/profile'
    | '/dashboard/(card-routes)/'
    | '/dashboard/request-management/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/auth/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/(card-routes)",
        "/dashboard/settings",
        "/dashboard/staff-management",
        "/dashboard/request-management/$id",
        "/dashboard/request-management/new",
        "/dashboard/request-management/"
      ]
    },
    "/dashboard/(card-routes)": {
      "filePath": "dashboard/(card-routes)/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/(card-routes)/inventory",
        "/dashboard/(card-routes)/"
      ]
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/settings/profile",
        "/dashboard/settings/"
      ]
    },
    "/auth/login": {
      "filePath": "auth.login.tsx"
    },
    "/dashboard/staff-management": {
      "filePath": "dashboard/staff-management.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/(card-routes)/inventory": {
      "filePath": "dashboard/(card-routes)/inventory.tsx",
      "parent": "/dashboard/(card-routes)"
    },
    "/dashboard/request-management/$id": {
      "filePath": "dashboard/request-management/$id.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/request-management/new": {
      "filePath": "dashboard/request-management/new.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings/profile": {
      "filePath": "dashboard/settings/profile.tsx",
      "parent": "/dashboard/settings"
    },
    "/dashboard/(card-routes)/": {
      "filePath": "dashboard/(card-routes)/index.tsx",
      "parent": "/dashboard/(card-routes)"
    },
    "/dashboard/request-management/": {
      "filePath": "dashboard/request-management/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings/": {
      "filePath": "dashboard/settings/index.tsx",
      "parent": "/dashboard/settings"
    }
  }
}
ROUTE_MANIFEST_END */
